// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module AES128Encrypt_Sbox (
        ap_ready,
        in_val,
        ap_return
);


output   ap_ready;
input  [7:0] in_val;
output  [7:0] ap_return;

wire   [0:0] tmp_3_fu_140_p3;
wire   [1:0] trunc_ln75_fu_148_p1;
wire   [6:0] and_ln_fu_152_p4;
wire   [7:0] zext_ln75_fu_162_p1;
wire   [0:0] tmp_4_fu_172_p3;
wire   [0:0] tmp_5_fu_180_p3;
wire   [6:0] and_ln75_1_fu_188_p7;
wire   [7:0] zext_ln75_1_fu_204_p1;
wire   [0:0] tmp_6_fu_214_p3;
wire   [3:0] tmp_9_fu_222_p4;
wire   [7:0] and_ln75_2_fu_232_p5;
wire   [1:0] tmp_s_fu_250_p4;
wire   [1:0] tmp_7_fu_260_p4;
wire   [7:0] and_ln75_3_fu_270_p5;
wire   [0:0] tmp_8_fu_288_p3;
wire   [2:0] tmp_10_fu_296_p4;
wire   [7:0] and_ln75_4_fu_306_p7;
wire   [1:0] tmp_11_fu_328_p4;
wire   [7:0] and_ln75_5_fu_338_p7;
wire   [7:0] and_ln75_6_fu_360_p5;
wire   [7:0] and_ln75_7_fu_378_p5;
reg   [0:0] xor_reduce_i_7_i_fu_390_p2;
reg   [0:0] xor_reduce_i_6_i_fu_372_p2;
reg   [0:0] xor_reduce_i_5_i_fu_354_p2;
reg   [0:0] xor_reduce_i_4_i_fu_322_p2;
reg   [0:0] xor_reduce_i_3_i_fu_282_p2;
reg   [0:0] xor_reduce_i_2_i_fu_244_p2;
reg   [0:0] xor_reduce_i_1_i_fu_208_p2;
reg   [0:0] xor_reduce_i_i_fu_166_p2;
wire   [0:0] xor_ln96_fu_440_p2;
wire   [0:0] xor_ln94_fu_428_p2;
wire   [0:0] xor_ln96_1_fu_446_p2;
wire   [0:0] xor_ln95_fu_434_p2;
wire   [0:0] xor_ln106_fu_458_p2;
wire   [0:0] xor_ln106_1_fu_464_p2;
wire   [0:0] xor_ln105_fu_452_p2;
wire   [0:0] xor_ln106_2_fu_470_p2;
wire   [3:0] g0_fu_416_p5;
wire   [3:0] g1_fu_396_p5;
wire   [3:0] g0_plus_g1_fu_488_p2;
wire   [1:0] x0_fu_512_p1;
wire   [1:0] x1_fu_494_p4;
wire   [0:0] trunc_ln124_fu_516_p1;
wire   [0:0] tmp_12_fu_504_p3;
wire   [1:0] y0_fu_528_p3;
wire   [1:0] y1_fu_520_p3;
wire   [1:0] and_ln54_fu_560_p2;
wire   [0:0] tmp_13_fu_572_p3;
wire   [0:0] and_ln54_2_fu_580_p2;
wire   [0:0] tmp_14_fu_592_p3;
wire   [0:0] xor_ln54_fu_586_p2;
wire   [0:0] and_ln54_3_fu_600_p2;
wire   [0:0] and_ln54_1_fu_566_p2;
wire   [1:0] y_3_fu_548_p2;
wire   [1:0] x_fu_536_p2;
wire   [0:0] xor_ln51_fu_554_p2;
wire   [0:0] xor_ln133_fu_542_p2;
wire   [1:0] and_ln54_4_fu_618_p2;
wire   [0:0] tmp_16_fu_638_p3;
wire   [0:0] tmp_15_fu_630_p3;
wire   [0:0] and_ln54_6_fu_646_p2;
wire   [0:0] tmp_17_fu_658_p3;
wire   [0:0] xor_ln54_1_fu_652_p2;
wire   [0:0] and_ln54_7_fu_666_p2;
wire   [0:0] and_ln54_5_fu_624_p2;
wire   [0:0] xor_ln54_10_fu_672_p2;
wire   [0:0] xor_ln55_1_fu_678_p2;
wire   [1:0] and_ln54_8_fu_692_p2;
wire   [0:0] tmp_18_fu_704_p3;
wire   [0:0] and_ln54_10_fu_712_p2;
wire   [0:0] tmp_19_fu_724_p3;
wire   [0:0] xor_ln54_2_fu_718_p2;
wire   [0:0] and_ln54_11_fu_732_p2;
wire   [0:0] and_ln54_9_fu_698_p2;
wire   [0:0] xor_ln54_11_fu_738_p2;
wire   [0:0] xor_ln55_2_fu_744_p2;
wire   [0:0] xor_ln55_fu_612_p2;
wire   [0:0] xor_ln54_9_fu_606_p2;
wire   [0:0] xor_ln63_fu_758_p2;
wire   [1:0] m_1_fu_750_p3;
wire   [1:0] m_fu_684_p3;
wire   [1:0] y_fu_764_p3;
wire   [1:0] m0_fu_772_p2;
wire   [1:0] m1_fu_778_p2;
wire   [0:0] xor_ln146_fu_784_p2;
wire   [3:0] g0_plus_g1_x_g0_fu_796_p3;
wire   [3:0] y_13_fu_476_p5;
wire   [1:0] tmp_2_fu_822_p3;
wire   [2:0] tmp_1_fu_814_p3;
wire   [2:0] tmp_fu_804_p4;
wire   [0:0] xor_ln181_fu_790_p2;
wire   [3:0] gf4_inv_in_fu_830_p2;
wire   [2:0] tmp_21_fu_862_p4;
wire   [3:0] and_ln1_fu_872_p3;
wire   [0:0] tmp_20_fu_854_p3;
wire   [0:0] icmp_ln155_fu_880_p2;
wire   [0:0] trunc_ln155_fu_892_p1;
wire   [3:0] and_ln155_1_fu_896_p4;
wire   [0:0] xor_ln155_fu_886_p2;
wire   [0:0] icmp_ln155_1_fu_906_p2;
wire   [2:0] xor_ln181_3_fu_842_p2;
wire   [0:0] xor_ln155_1_fu_912_p2;
wire   [0:0] tmp_22_fu_918_p3;
wire   [1:0] tmp_23_fu_932_p4;
wire   [3:0] and_ln2_fu_942_p4;
wire   [0:0] icmp_ln156_fu_952_p2;
wire   [0:0] xor_ln156_fu_958_p2;
wire   [0:0] xor_ln156_1_fu_964_p2;
wire   [1:0] tmp_24_fu_976_p4;
wire   [2:0] and_ln156_1_fu_986_p3;
wire   [0:0] xor_ln156_2_fu_970_p2;
wire   [0:0] icmp_ln156_1_fu_994_p2;
wire   [0:0] tmp_25_fu_1006_p3;
wire   [3:0] and_ln3_fu_1014_p5;
wire   [1:0] trunc_ln157_fu_1032_p1;
wire   [3:0] and_ln157_1_fu_1036_p4;
wire   [0:0] trunc_ln157_1_fu_1052_p1;
wire   [2:0] and_ln157_2_fu_1056_p4;
wire   [0:0] icmp_ln157_2_fu_1066_p2;
wire   [0:0] icmp_ln157_1_fu_1046_p2;
wire   [0:0] xor_ln157_fu_1072_p2;
wire   [0:0] xor_ln157_1_fu_1078_p2;
wire   [1:0] xor_ln181_2_fu_836_p2;
wire   [0:0] xor_ln157_2_fu_1084_p2;
wire   [0:0] tmp_26_fu_1090_p3;
wire   [0:0] icmp_ln157_fu_1026_p2;
wire   [0:0] xor_ln158_1_fu_1110_p2;
wire   [0:0] xor_ln158_fu_1104_p2;
wire   [0:0] icmp_ln158_fu_1122_p2;
wire   [0:0] xor_ln158_2_fu_1116_p2;
wire   [0:0] xor_ln158_4_fu_1134_p2;
wire   [0:0] xor_ln158_5_fu_1140_p2;
wire   [0:0] xor_ln158_3_fu_1128_p2;
wire   [0:0] xor_ln158_6_fu_1146_p2;
wire   [0:0] xor_ln181_4_fu_848_p2;
wire   [0:0] xor_ln155_2_fu_926_p2;
wire   [0:0] xor_ln156_3_fu_1000_p2;
wire   [0:0] xor_ln157_3_fu_1098_p2;
wire   [0:0] xor_ln158_7_fu_1152_p2;
wire   [1:0] x0_1_fu_1166_p3;
wire   [1:0] x1_1_fu_1158_p3;
wire   [1:0] y0_1_fu_408_p3;
wire   [1:0] y1_1_fu_1174_p3;
wire   [1:0] and_ln54_12_fu_1206_p2;
wire   [0:0] tmp_27_fu_1218_p3;
wire   [0:0] and_ln54_14_fu_1226_p2;
wire   [0:0] xor_ln54_3_fu_1232_p2;
wire   [0:0] and_ln54_15_fu_1238_p2;
wire   [0:0] and_ln54_13_fu_1212_p2;
wire   [1:0] y_7_fu_1194_p2;
wire   [1:0] x_7_fu_1182_p2;
wire   [0:0] xor_ln51_1_fu_1200_p2;
wire   [0:0] xor_ln133_2_fu_1188_p2;
wire   [1:0] and_ln54_16_fu_1256_p2;
wire   [0:0] tmp_29_fu_1276_p3;
wire   [0:0] tmp_28_fu_1268_p3;
wire   [0:0] and_ln54_18_fu_1284_p2;
wire   [0:0] tmp_30_fu_1296_p3;
wire   [0:0] xor_ln54_4_fu_1290_p2;
wire   [0:0] and_ln54_19_fu_1304_p2;
wire   [0:0] and_ln54_17_fu_1262_p2;
wire   [0:0] xor_ln54_13_fu_1310_p2;
wire   [0:0] xor_ln55_4_fu_1316_p2;
wire   [1:0] and_ln54_20_fu_1330_p2;
wire   [0:0] tmp_31_fu_1342_p3;
wire   [0:0] and_ln54_22_fu_1350_p2;
wire   [0:0] xor_ln54_5_fu_1356_p2;
wire   [0:0] and_ln54_23_fu_1362_p2;
wire   [0:0] and_ln54_21_fu_1336_p2;
wire   [0:0] xor_ln54_14_fu_1368_p2;
wire   [0:0] xor_ln55_5_fu_1374_p2;
wire   [0:0] xor_ln55_3_fu_1250_p2;
wire   [0:0] xor_ln54_12_fu_1244_p2;
wire   [0:0] xor_ln63_1_fu_1388_p2;
wire   [1:0] m_3_fu_1380_p3;
wire   [1:0] m_2_fu_1322_p3;
wire   [1:0] y_14_fu_1394_p3;
wire   [1:0] and_ln54_24_fu_1414_p2;
wire   [0:0] tmp_32_fu_1426_p3;
wire   [0:0] and_ln54_26_fu_1434_p2;
wire   [0:0] xor_ln54_6_fu_1440_p2;
wire   [0:0] and_ln54_27_fu_1446_p2;
wire   [0:0] and_ln54_25_fu_1420_p2;
wire   [1:0] and_ln54_28_fu_1464_p2;
wire   [0:0] tmp_33_fu_1476_p3;
wire   [0:0] and_ln54_30_fu_1484_p2;
wire   [0:0] xor_ln54_7_fu_1490_p2;
wire   [0:0] and_ln54_31_fu_1496_p2;
wire   [0:0] and_ln54_29_fu_1470_p2;
wire   [0:0] xor_ln54_16_fu_1502_p2;
wire   [0:0] xor_ln55_7_fu_1508_p2;
wire   [1:0] and_ln54_32_fu_1522_p2;
wire   [0:0] tmp_34_fu_1534_p3;
wire   [0:0] and_ln54_34_fu_1542_p2;
wire   [0:0] xor_ln54_8_fu_1548_p2;
wire   [0:0] and_ln54_35_fu_1554_p2;
wire   [0:0] and_ln54_33_fu_1528_p2;
wire   [0:0] xor_ln54_17_fu_1560_p2;
wire   [0:0] xor_ln55_8_fu_1566_p2;
wire   [0:0] xor_ln55_6_fu_1458_p2;
wire   [0:0] xor_ln54_15_fu_1452_p2;
wire   [0:0] xor_ln63_2_fu_1580_p2;
wire   [1:0] m_5_fu_1572_p3;
wire   [1:0] m_4_fu_1514_p3;
wire   [1:0] y_15_fu_1586_p3;
wire   [1:0] m0_2_fu_1594_p2;
wire   [1:0] m1_2_fu_1600_p2;
wire   [0:0] xor_ln185_fu_1606_p2;
wire   [1:0] m1_1_fu_1408_p2;
wire   [0:0] trunc_ln85_fu_1612_p1;
wire   [0:0] trunc_ln85_1_fu_1616_p1;
wire   [6:0] and_ln4_fu_1620_p7;
wire   [7:0] zext_ln85_fu_1636_p1;
wire   [5:0] and_ln85_1_fu_1646_p3;
wire   [7:0] zext_ln85_1_fu_1654_p1;
wire   [1:0] m0_1_fu_1402_p2;
wire   [0:0] tmp_35_fu_1664_p3;
wire   [0:0] trunc_ln85_2_fu_1680_p1;
wire   [0:0] tmp_36_fu_1672_p3;
wire   [7:0] and_ln85_2_fu_1684_p7;
wire   [5:0] and_ln85_3_fu_1706_p5;
wire   [7:0] zext_ln85_2_fu_1718_p1;
wire   [6:0] and_ln85_4_fu_1728_p7;
wire   [7:0] zext_ln85_3_fu_1744_p1;
wire   [0:0] tmp_37_fu_1754_p3;
wire   [6:0] and_ln85_5_fu_1762_p6;
wire   [7:0] zext_ln85_4_fu_1776_p1;
wire   [6:0] and_ln85_6_fu_1786_p5;
wire   [7:0] zext_ln85_5_fu_1798_p1;
wire   [7:0] and_ln85_7_fu_1808_p6;
reg   [0:0] xor_reduce_i_4_i1_fu_1748_p2;
reg   [0:0] xor_reduce_i_3_i1_fu_1722_p2;
reg   [0:0] xor_reduce_i_2_i1_fu_1700_p2;
reg   [0:0] xor_reduce_i_1_i1_fu_1658_p2;
reg   [0:0] xor_reduce_i_i1_fu_1640_p2;
reg   [0:0] xor_reduce_i_7_i1_fu_1822_p2;
reg   [0:0] xor_reduce_i_6_i1_fu_1802_p2;
reg   [0:0] xor_reduce_i_5_i1_fu_1780_p2;
wire   [7:0] and_ln5_fu_1842_p7;
wire   [7:0] and_ln117_1_fu_1864_p7;
wire   [7:0] and_ln117_2_fu_1886_p7;
wire   [7:0] and_ln117_3_fu_1908_p7;
wire   [4:0] y_22_cast_fu_1828_p6;
wire   [7:0] zext_ln117_fu_1930_p1;
wire   [5:0] and_ln117_4_fu_1940_p7;
wire   [7:0] zext_ln117_1_fu_1956_p1;
wire   [6:0] and_ln117_5_fu_1966_p7;
wire   [7:0] zext_ln117_2_fu_1982_p1;
wire   [7:0] and_ln117_6_fu_1992_p7;
reg   [0:0] xor_reduce_i_7_i2_fu_2008_p2;
reg   [0:0] xor_reduce_i_6_i2_fu_1986_p2;
reg   [0:0] xor_reduce_i_5_i2_fu_1960_p2;
reg   [0:0] xor_reduce_i_4_i2_fu_1934_p2;
reg   [0:0] xor_reduce_i_3_i2_fu_1924_p2;
reg   [0:0] xor_reduce_i_2_i2_fu_1902_p2;
reg   [0:0] xor_reduce_i_1_i2_fu_1880_p2;
reg   [0:0] xor_reduce_i_i2_fu_1858_p2;
wire   [7:0] y_12_fu_2014_p9;

assign and_ln117_1_fu_1864_p7 = {{{{{{xor_reduce_i_7_i1_fu_1822_p2}, {xor_reduce_i_6_i1_fu_1802_p2}}, {xor_reduce_i_5_i1_fu_1780_p2}}, {3'd0}}, {xor_reduce_i_1_i1_fu_1658_p2}}, {xor_reduce_i_i1_fu_1640_p2}};

assign and_ln117_2_fu_1886_p7 = {{{{{{xor_reduce_i_7_i1_fu_1822_p2}, {xor_reduce_i_6_i1_fu_1802_p2}}, {3'd0}}, {xor_reduce_i_2_i1_fu_1700_p2}}, {xor_reduce_i_1_i1_fu_1658_p2}}, {xor_reduce_i_i1_fu_1640_p2}};

assign and_ln117_3_fu_1908_p7 = {{{{{{xor_reduce_i_7_i1_fu_1822_p2}, {3'd0}}, {xor_reduce_i_3_i1_fu_1722_p2}}, {xor_reduce_i_2_i1_fu_1700_p2}}, {xor_reduce_i_1_i1_fu_1658_p2}}, {xor_reduce_i_i1_fu_1640_p2}};

assign and_ln117_4_fu_1940_p7 = {{{{{{xor_reduce_i_5_i1_fu_1780_p2}, {xor_reduce_i_4_i1_fu_1748_p2}}, {xor_reduce_i_3_i1_fu_1722_p2}}, {xor_reduce_i_2_i1_fu_1700_p2}}, {xor_reduce_i_1_i1_fu_1658_p2}}, {1'd0}};

assign and_ln117_5_fu_1966_p7 = {{{{{{xor_reduce_i_6_i1_fu_1802_p2}, {xor_reduce_i_5_i1_fu_1780_p2}}, {xor_reduce_i_4_i1_fu_1748_p2}}, {xor_reduce_i_3_i1_fu_1722_p2}}, {xor_reduce_i_2_i1_fu_1700_p2}}, {2'd0}};

assign and_ln117_6_fu_1992_p7 = {{{{{{xor_reduce_i_7_i1_fu_1822_p2}, {xor_reduce_i_6_i1_fu_1802_p2}}, {xor_reduce_i_5_i1_fu_1780_p2}}, {xor_reduce_i_4_i1_fu_1748_p2}}, {xor_reduce_i_3_i1_fu_1722_p2}}, {3'd0}};

assign and_ln155_1_fu_896_p4 = {{{tmp_20_fu_854_p3}, {2'd0}}, {trunc_ln155_fu_892_p1}};

assign and_ln156_1_fu_986_p3 = {{tmp_24_fu_976_p4}, {1'd0}};

assign and_ln157_1_fu_1036_p4 = {{{tmp_20_fu_854_p3}, {1'd0}}, {trunc_ln157_fu_1032_p1}};

assign and_ln157_2_fu_1056_p4 = {{{tmp_22_fu_918_p3}, {1'd0}}, {trunc_ln157_1_fu_1052_p1}};

assign and_ln1_fu_872_p3 = {{tmp_21_fu_862_p4}, {1'd0}};

assign and_ln2_fu_942_p4 = {{{tmp_23_fu_932_p4}, {1'd0}}, {trunc_ln155_fu_892_p1}};

assign and_ln3_fu_1014_p5 = {{{{tmp_20_fu_854_p3}, {1'd0}}, {tmp_25_fu_1006_p3}}, {1'd0}};

assign and_ln4_fu_1620_p7 = {{{{{{xor_ln185_fu_1606_p2}, {m1_1_fu_1408_p2}}, {1'd0}}, {trunc_ln85_fu_1612_p1}}, {1'd0}}, {trunc_ln85_1_fu_1616_p1}};

assign and_ln54_10_fu_712_p2 = (xor_reduce_i_1_i_fu_208_p2 & trunc_ln124_fu_516_p1);

assign and_ln54_11_fu_732_p2 = (xor_reduce_i_i_fu_166_p2 & tmp_19_fu_724_p3);

assign and_ln54_12_fu_1206_p2 = (y1_1_fu_1174_p3 & x1_1_fu_1158_p3);

assign and_ln54_13_fu_1212_p2 = (xor_reduce_i_6_i_fu_372_p2 & xor_ln156_3_fu_1000_p2);

assign and_ln54_14_fu_1226_p2 = (xor_reduce_i_7_i_fu_390_p2 & xor_ln156_3_fu_1000_p2);

assign and_ln54_15_fu_1238_p2 = (xor_reduce_i_6_i_fu_372_p2 & xor_ln155_2_fu_926_p2);

assign and_ln54_16_fu_1256_p2 = (y_7_fu_1194_p2 & x_7_fu_1182_p2);

assign and_ln54_17_fu_1262_p2 = (xor_ln51_1_fu_1200_p2 & xor_ln133_2_fu_1188_p2);

assign and_ln54_18_fu_1284_p2 = (xor_ln133_2_fu_1188_p2 & tmp_29_fu_1276_p3);

assign and_ln54_19_fu_1304_p2 = (xor_ln51_1_fu_1200_p2 & tmp_30_fu_1296_p3);

assign and_ln54_1_fu_566_p2 = (xor_reduce_i_2_i_fu_244_p2 & tmp_12_fu_504_p3);

assign and_ln54_20_fu_1330_p2 = (y0_1_fu_408_p3 & x0_1_fu_1166_p3);

assign and_ln54_21_fu_1336_p2 = (xor_reduce_i_4_i_fu_322_p2 & xor_ln158_7_fu_1152_p2);

assign and_ln54_22_fu_1350_p2 = (xor_reduce_i_5_i_fu_354_p2 & xor_ln158_7_fu_1152_p2);

assign and_ln54_23_fu_1362_p2 = (xor_reduce_i_4_i_fu_322_p2 & xor_ln157_3_fu_1098_p2);

assign and_ln54_24_fu_1414_p2 = (x1_fu_494_p4 & x1_1_fu_1158_p3);

assign and_ln54_25_fu_1420_p2 = (xor_ln156_3_fu_1000_p2 & tmp_12_fu_504_p3);

assign and_ln54_26_fu_1434_p2 = (xor_ln156_3_fu_1000_p2 & tmp_14_fu_592_p3);

assign and_ln54_27_fu_1446_p2 = (xor_ln155_2_fu_926_p2 & tmp_12_fu_504_p3);

assign and_ln54_28_fu_1464_p2 = (x_fu_536_p2 & x_7_fu_1182_p2);

assign and_ln54_29_fu_1470_p2 = (xor_ln133_fu_542_p2 & xor_ln133_2_fu_1188_p2);

assign and_ln54_2_fu_580_p2 = (xor_reduce_i_3_i_fu_282_p2 & tmp_12_fu_504_p3);

assign and_ln54_30_fu_1484_p2 = (xor_ln133_2_fu_1188_p2 & tmp_17_fu_658_p3);

assign and_ln54_31_fu_1496_p2 = (xor_ln133_fu_542_p2 & tmp_30_fu_1296_p3);

assign and_ln54_32_fu_1522_p2 = (x0_fu_512_p1 & x0_1_fu_1166_p3);

assign and_ln54_33_fu_1528_p2 = (xor_ln158_7_fu_1152_p2 & trunc_ln124_fu_516_p1);

assign and_ln54_34_fu_1542_p2 = (xor_ln158_7_fu_1152_p2 & tmp_19_fu_724_p3);

assign and_ln54_35_fu_1554_p2 = (xor_ln157_3_fu_1098_p2 & trunc_ln124_fu_516_p1);

assign and_ln54_3_fu_600_p2 = (xor_reduce_i_2_i_fu_244_p2 & tmp_14_fu_592_p3);

assign and_ln54_4_fu_618_p2 = (y_3_fu_548_p2 & x_fu_536_p2);

assign and_ln54_5_fu_624_p2 = (xor_ln51_fu_554_p2 & xor_ln133_fu_542_p2);

assign and_ln54_6_fu_646_p2 = (xor_ln133_fu_542_p2 & tmp_16_fu_638_p3);

assign and_ln54_7_fu_666_p2 = (xor_ln51_fu_554_p2 & tmp_17_fu_658_p3);

assign and_ln54_8_fu_692_p2 = (y0_fu_528_p3 & x0_fu_512_p1);

assign and_ln54_9_fu_698_p2 = (xor_reduce_i_i_fu_166_p2 & trunc_ln124_fu_516_p1);

assign and_ln54_fu_560_p2 = (y1_fu_520_p3 & x1_fu_494_p4);

assign and_ln5_fu_1842_p7 = {{{{{{xor_reduce_i_7_i1_fu_1822_p2}, {xor_reduce_i_6_i1_fu_1802_p2}}, {xor_reduce_i_5_i1_fu_1780_p2}}, {xor_reduce_i_4_i1_fu_1748_p2}}, {3'd0}}, {xor_reduce_i_i1_fu_1640_p2}};

assign and_ln75_1_fu_188_p7 = {{{{{{tmp_3_fu_140_p3}, {1'd0}}, {tmp_4_fu_172_p3}}, {2'd0}}, {tmp_5_fu_180_p3}}, {1'd0}};

assign and_ln75_2_fu_232_p5 = {{{{tmp_6_fu_214_p3}, {2'd0}}, {tmp_9_fu_222_p4}}, {1'd0}};

assign and_ln75_3_fu_270_p5 = {{{{tmp_s_fu_250_p4}, {3'd0}}, {tmp_7_fu_260_p4}}, {1'd0}};

assign and_ln75_4_fu_306_p7 = {{{{{{tmp_6_fu_214_p3}, {1'd0}}, {tmp_8_fu_288_p3}}, {1'd0}}, {tmp_10_fu_296_p4}}, {1'd0}};

assign and_ln75_5_fu_338_p7 = {{{{{{tmp_6_fu_214_p3}, {1'd0}}, {tmp_8_fu_288_p3}}, {1'd0}}, {tmp_11_fu_328_p4}}, {2'd0}};

assign and_ln75_6_fu_360_p5 = {{{{tmp_s_fu_250_p4}, {1'd0}}, {tmp_9_fu_222_p4}}, {1'd0}};

assign and_ln75_7_fu_378_p5 = {{{{tmp_6_fu_214_p3}, {1'd0}}, {tmp_8_fu_288_p3}}, {5'd0}};

assign and_ln85_1_fu_1646_p3 = {{m1_1_fu_1408_p2}, {4'd0}};

assign and_ln85_2_fu_1684_p7 = {{{{{{tmp_35_fu_1664_p3}, {2'd0}}, {trunc_ln85_2_fu_1680_p1}}, {m0_2_fu_1594_p2}}, {tmp_36_fu_1672_p3}}, {1'd0}};

assign and_ln85_3_fu_1706_p5 = {{{{m1_1_fu_1408_p2}, {m0_2_fu_1594_p2}}, {tmp_36_fu_1672_p3}}, {1'd0}};

assign and_ln85_4_fu_1728_p7 = {{{{{{xor_ln185_fu_1606_p2}, {m1_1_fu_1408_p2}}, {1'd0}}, {trunc_ln85_fu_1612_p1}}, {tmp_36_fu_1672_p3}}, {1'd0}};

assign and_ln85_5_fu_1762_p6 = {{{{{xor_ln185_fu_1606_p2}, {tmp_37_fu_1754_p3}}, {3'd0}}, {tmp_36_fu_1672_p3}}, {1'd0}};

assign and_ln85_6_fu_1786_p5 = {{{{xor_ln185_fu_1606_p2}, {3'd0}}, {trunc_ln85_fu_1612_p1}}, {2'd0}};

assign and_ln85_7_fu_1808_p6 = {{{{{m0_1_fu_1402_p2}, {tmp_37_fu_1754_p3}}, {3'd0}}, {tmp_36_fu_1672_p3}}, {1'd0}};

assign and_ln_fu_152_p4 = {{{tmp_3_fu_140_p3}, {4'd0}}, {trunc_ln75_fu_148_p1}};

assign ap_ready = 1'b1;

assign g0_fu_416_p5 = {{{{xor_reduce_i_3_i_fu_282_p2}, {xor_reduce_i_2_i_fu_244_p2}}, {xor_reduce_i_1_i_fu_208_p2}}, {xor_reduce_i_i_fu_166_p2}};

assign g0_plus_g1_fu_488_p2 = (g1_fu_396_p5 ^ g0_fu_416_p5);

assign g0_plus_g1_x_g0_fu_796_p3 = {{m0_fu_772_p2}, {m1_fu_778_p2}};

assign g1_fu_396_p5 = {{{{xor_reduce_i_7_i_fu_390_p2}, {xor_reduce_i_6_i_fu_372_p2}}, {xor_reduce_i_5_i_fu_354_p2}}, {xor_reduce_i_4_i_fu_322_p2}};

assign gf4_inv_in_fu_830_p2 = (y_13_fu_476_p5 ^ g0_plus_g1_x_g0_fu_796_p3);

assign m0_1_fu_1402_p2 = (m_3_fu_1380_p3 ^ m_2_fu_1322_p3);

assign m0_2_fu_1594_p2 = (m_5_fu_1572_p3 ^ m_4_fu_1514_p3);

assign m0_fu_772_p2 = (m_fu_684_p3 ^ m_1_fu_750_p3);

assign m1_1_fu_1408_p2 = (y_14_fu_1394_p3 ^ m_3_fu_1380_p3);

assign m1_2_fu_1600_p2 = (y_15_fu_1586_p3 ^ m_5_fu_1572_p3);

assign m1_fu_778_p2 = (y_fu_764_p3 ^ m_1_fu_750_p3);

assign m_1_fu_750_p3 = {{xor_ln54_11_fu_738_p2}, {xor_ln55_2_fu_744_p2}};

assign m_2_fu_1322_p3 = {{xor_ln54_13_fu_1310_p2}, {xor_ln55_4_fu_1316_p2}};

assign m_3_fu_1380_p3 = {{xor_ln54_14_fu_1368_p2}, {xor_ln55_5_fu_1374_p2}};

assign m_4_fu_1514_p3 = {{xor_ln54_16_fu_1502_p2}, {xor_ln55_7_fu_1508_p2}};

assign m_5_fu_1572_p3 = {{xor_ln54_17_fu_1560_p2}, {xor_ln55_8_fu_1566_p2}};

assign m_fu_684_p3 = {{xor_ln54_10_fu_672_p2}, {xor_ln55_1_fu_678_p2}};

assign tmp_10_fu_296_p4 = {{in_val[3:1]}};

assign tmp_11_fu_328_p4 = {{in_val[3:2]}};

assign tmp_12_fu_504_p3 = g0_plus_g1_fu_488_p2[32'd2];

assign tmp_13_fu_572_p3 = and_ln54_fu_560_p2[32'd1];

assign tmp_14_fu_592_p3 = g0_plus_g1_fu_488_p2[32'd3];

assign tmp_15_fu_630_p3 = and_ln54_4_fu_618_p2[32'd1];

assign tmp_16_fu_638_p3 = y_3_fu_548_p2[32'd1];

assign tmp_17_fu_658_p3 = x_fu_536_p2[32'd1];

assign tmp_18_fu_704_p3 = and_ln54_8_fu_692_p2[32'd1];

assign tmp_19_fu_724_p3 = g0_plus_g1_fu_488_p2[32'd1];

assign tmp_1_fu_814_p3 = {{xor_ln146_fu_784_p2}, {m1_fu_778_p2}};

assign tmp_20_fu_854_p3 = gf4_inv_in_fu_830_p2[32'd3];

assign tmp_21_fu_862_p4 = {{gf4_inv_in_fu_830_p2[3:1]}};

assign tmp_22_fu_918_p3 = xor_ln181_3_fu_842_p2[32'd2];

assign tmp_23_fu_932_p4 = {{gf4_inv_in_fu_830_p2[3:2]}};

assign tmp_24_fu_976_p4 = {{xor_ln181_3_fu_842_p2[2:1]}};

assign tmp_25_fu_1006_p3 = gf4_inv_in_fu_830_p2[32'd1];

assign tmp_26_fu_1090_p3 = xor_ln181_2_fu_836_p2[32'd1];

assign tmp_27_fu_1218_p3 = and_ln54_12_fu_1206_p2[32'd1];

assign tmp_28_fu_1268_p3 = and_ln54_16_fu_1256_p2[32'd1];

assign tmp_29_fu_1276_p3 = y_7_fu_1194_p2[32'd1];

assign tmp_2_fu_822_p3 = {{xor_reduce_i_7_i_fu_390_p2}, {xor_ln94_fu_428_p2}};

assign tmp_30_fu_1296_p3 = x_7_fu_1182_p2[32'd1];

assign tmp_31_fu_1342_p3 = and_ln54_20_fu_1330_p2[32'd1];

assign tmp_32_fu_1426_p3 = and_ln54_24_fu_1414_p2[32'd1];

assign tmp_33_fu_1476_p3 = and_ln54_28_fu_1464_p2[32'd1];

assign tmp_34_fu_1534_p3 = and_ln54_32_fu_1522_p2[32'd1];

assign tmp_35_fu_1664_p3 = m0_1_fu_1402_p2[32'd1];

assign tmp_36_fu_1672_p3 = m1_2_fu_1600_p2[32'd1];

assign tmp_37_fu_1754_p3 = m1_1_fu_1408_p2[32'd1];

assign tmp_3_fu_140_p3 = in_val[32'd6];

assign tmp_4_fu_172_p3 = in_val[32'd4];

assign tmp_5_fu_180_p3 = in_val[32'd1];

assign tmp_6_fu_214_p3 = in_val[32'd7];

assign tmp_7_fu_260_p4 = {{in_val[2:1]}};

assign tmp_8_fu_288_p3 = in_val[32'd5];

assign tmp_9_fu_222_p4 = {{in_val[4:1]}};

assign tmp_fu_804_p4 = {{{xor_ln106_2_fu_470_p2}, {xor_reduce_i_7_i_fu_390_p2}}, {xor_ln94_fu_428_p2}};

assign tmp_s_fu_250_p4 = {{in_val[7:6]}};

assign trunc_ln124_fu_516_p1 = g0_plus_g1_fu_488_p2[0:0];

assign trunc_ln155_fu_892_p1 = gf4_inv_in_fu_830_p2[0:0];

assign trunc_ln157_1_fu_1052_p1 = xor_ln181_3_fu_842_p2[0:0];

assign trunc_ln157_fu_1032_p1 = gf4_inv_in_fu_830_p2[1:0];

assign trunc_ln75_fu_148_p1 = in_val[1:0];

assign trunc_ln85_1_fu_1616_p1 = m1_2_fu_1600_p2[0:0];

assign trunc_ln85_2_fu_1680_p1 = m1_1_fu_1408_p2[0:0];

assign trunc_ln85_fu_1612_p1 = m0_2_fu_1594_p2[0:0];

assign x0_1_fu_1166_p3 = {{xor_ln157_3_fu_1098_p2}, {xor_ln158_7_fu_1152_p2}};

assign x0_fu_512_p1 = g0_plus_g1_fu_488_p2[1:0];

assign x1_1_fu_1158_p3 = {{xor_ln155_2_fu_926_p2}, {xor_ln156_3_fu_1000_p2}};

assign x1_fu_494_p4 = {{g0_plus_g1_fu_488_p2[3:2]}};

assign x_7_fu_1182_p2 = (x1_1_fu_1158_p3 ^ x0_1_fu_1166_p3);

assign x_fu_536_p2 = (x1_fu_494_p4 ^ x0_fu_512_p1);

assign xor_ln105_fu_452_p2 = (xor_ln96_1_fu_446_p2 ^ xor_ln94_fu_428_p2);

assign xor_ln106_1_fu_464_p2 = (xor_ln94_fu_428_p2 ^ xor_ln106_fu_458_p2);

assign xor_ln106_2_fu_470_p2 = (xor_ln96_1_fu_446_p2 ^ xor_ln106_1_fu_464_p2);

assign xor_ln106_fu_458_p2 = (xor_reduce_i_7_i_fu_390_p2 ^ xor_ln95_fu_434_p2);

assign xor_ln133_2_fu_1188_p2 = (xor_ln158_7_fu_1152_p2 ^ xor_ln156_3_fu_1000_p2);

assign xor_ln133_fu_542_p2 = (trunc_ln124_fu_516_p1 ^ tmp_12_fu_504_p3);

assign xor_ln146_fu_784_p2 = (xor_ln55_2_fu_744_p2 ^ xor_ln55_1_fu_678_p2);

assign xor_ln155_1_fu_912_p2 = (xor_ln155_fu_886_p2 ^ icmp_ln155_1_fu_906_p2);

assign xor_ln155_2_fu_926_p2 = (xor_ln155_1_fu_912_p2 ^ tmp_22_fu_918_p3);

assign xor_ln155_fu_886_p2 = (tmp_20_fu_854_p3 ^ icmp_ln155_fu_880_p2);

assign xor_ln156_1_fu_964_p2 = (xor_ln156_fu_958_p2 ^ icmp_ln155_1_fu_906_p2);

assign xor_ln156_2_fu_970_p2 = (xor_ln156_1_fu_964_p2 ^ tmp_22_fu_918_p3);

assign xor_ln156_3_fu_1000_p2 = (xor_ln156_2_fu_970_p2 ^ icmp_ln156_1_fu_994_p2);

assign xor_ln156_fu_958_p2 = (icmp_ln156_fu_952_p2 ^ icmp_ln155_fu_880_p2);

assign xor_ln157_1_fu_1078_p2 = (xor_ln157_fu_1072_p2 ^ tmp_22_fu_918_p3);

assign xor_ln157_2_fu_1084_p2 = (xor_ln157_1_fu_1078_p2 ^ xor_ln155_fu_886_p2);

assign xor_ln157_3_fu_1098_p2 = (xor_ln157_2_fu_1084_p2 ^ tmp_26_fu_1090_p3);

assign xor_ln157_fu_1072_p2 = (icmp_ln157_2_fu_1066_p2 ^ icmp_ln157_1_fu_1046_p2);

assign xor_ln158_1_fu_1110_p2 = (icmp_ln157_1_fu_1046_p2 ^ icmp_ln155_1_fu_906_p2);

assign xor_ln158_2_fu_1116_p2 = (xor_ln158_fu_1104_p2 ^ xor_ln158_1_fu_1110_p2);

assign xor_ln158_3_fu_1128_p2 = (tmp_26_fu_1090_p3 ^ tmp_22_fu_918_p3);

assign xor_ln158_4_fu_1134_p2 = (xor_ln158_2_fu_1116_p2 ^ icmp_ln158_fu_1122_p2);

assign xor_ln158_5_fu_1140_p2 = (xor_ln158_4_fu_1134_p2 ^ icmp_ln156_1_fu_994_p2);

assign xor_ln158_6_fu_1146_p2 = (xor_ln158_5_fu_1140_p2 ^ xor_ln158_3_fu_1128_p2);

assign xor_ln158_7_fu_1152_p2 = (xor_ln181_4_fu_848_p2 ^ xor_ln158_6_fu_1146_p2);

assign xor_ln158_fu_1104_p2 = (xor_ln156_fu_958_p2 ^ icmp_ln157_fu_1026_p2);

assign xor_ln181_2_fu_836_p2 = (tmp_2_fu_822_p3 ^ m1_fu_778_p2);

assign xor_ln181_3_fu_842_p2 = (tmp_fu_804_p4 ^ tmp_1_fu_814_p3);

assign xor_ln181_4_fu_848_p2 = (xor_ln94_fu_428_p2 ^ xor_ln181_fu_790_p2);

assign xor_ln181_fu_790_p2 = (xor_ln55_2_fu_744_p2 ^ xor_ln54_9_fu_606_p2);

assign xor_ln185_fu_1606_p2 = (xor_ln55_5_fu_1374_p2 ^ xor_ln55_4_fu_1316_p2);

assign xor_ln51_1_fu_1200_p2 = (xor_reduce_i_6_i_fu_372_p2 ^ xor_reduce_i_4_i_fu_322_p2);

assign xor_ln51_fu_554_p2 = (xor_reduce_i_i_fu_166_p2 ^ xor_reduce_i_2_i_fu_244_p2);

assign xor_ln54_10_fu_672_p2 = (xor_ln54_1_fu_652_p2 ^ and_ln54_7_fu_666_p2);

assign xor_ln54_11_fu_738_p2 = (xor_ln54_2_fu_718_p2 ^ and_ln54_11_fu_732_p2);

assign xor_ln54_12_fu_1244_p2 = (xor_ln54_3_fu_1232_p2 ^ and_ln54_15_fu_1238_p2);

assign xor_ln54_13_fu_1310_p2 = (xor_ln54_4_fu_1290_p2 ^ and_ln54_19_fu_1304_p2);

assign xor_ln54_14_fu_1368_p2 = (xor_ln54_5_fu_1356_p2 ^ and_ln54_23_fu_1362_p2);

assign xor_ln54_15_fu_1452_p2 = (xor_ln54_6_fu_1440_p2 ^ and_ln54_27_fu_1446_p2);

assign xor_ln54_16_fu_1502_p2 = (xor_ln54_7_fu_1490_p2 ^ and_ln54_31_fu_1496_p2);

assign xor_ln54_17_fu_1560_p2 = (xor_ln54_8_fu_1548_p2 ^ and_ln54_35_fu_1554_p2);

assign xor_ln54_1_fu_652_p2 = (tmp_15_fu_630_p3 ^ and_ln54_6_fu_646_p2);

assign xor_ln54_2_fu_718_p2 = (tmp_18_fu_704_p3 ^ and_ln54_10_fu_712_p2);

assign xor_ln54_3_fu_1232_p2 = (tmp_27_fu_1218_p3 ^ and_ln54_14_fu_1226_p2);

assign xor_ln54_4_fu_1290_p2 = (tmp_28_fu_1268_p3 ^ and_ln54_18_fu_1284_p2);

assign xor_ln54_5_fu_1356_p2 = (tmp_31_fu_1342_p3 ^ and_ln54_22_fu_1350_p2);

assign xor_ln54_6_fu_1440_p2 = (tmp_32_fu_1426_p3 ^ and_ln54_26_fu_1434_p2);

assign xor_ln54_7_fu_1490_p2 = (tmp_33_fu_1476_p3 ^ and_ln54_30_fu_1484_p2);

assign xor_ln54_8_fu_1548_p2 = (tmp_34_fu_1534_p3 ^ and_ln54_34_fu_1542_p2);

assign xor_ln54_9_fu_606_p2 = (xor_ln54_fu_586_p2 ^ and_ln54_3_fu_600_p2);

assign xor_ln54_fu_586_p2 = (tmp_13_fu_572_p3 ^ and_ln54_2_fu_580_p2);

assign xor_ln55_1_fu_678_p2 = (tmp_15_fu_630_p3 ^ and_ln54_5_fu_624_p2);

assign xor_ln55_2_fu_744_p2 = (tmp_18_fu_704_p3 ^ and_ln54_9_fu_698_p2);

assign xor_ln55_3_fu_1250_p2 = (tmp_27_fu_1218_p3 ^ and_ln54_13_fu_1212_p2);

assign xor_ln55_4_fu_1316_p2 = (tmp_28_fu_1268_p3 ^ and_ln54_17_fu_1262_p2);

assign xor_ln55_5_fu_1374_p2 = (tmp_31_fu_1342_p3 ^ and_ln54_21_fu_1336_p2);

assign xor_ln55_6_fu_1458_p2 = (tmp_32_fu_1426_p3 ^ and_ln54_25_fu_1420_p2);

assign xor_ln55_7_fu_1508_p2 = (tmp_33_fu_1476_p3 ^ and_ln54_29_fu_1470_p2);

assign xor_ln55_8_fu_1566_p2 = (tmp_34_fu_1534_p3 ^ and_ln54_33_fu_1528_p2);

assign xor_ln55_fu_612_p2 = (tmp_13_fu_572_p3 ^ and_ln54_1_fu_566_p2);

assign xor_ln63_1_fu_1388_p2 = (xor_ln55_3_fu_1250_p2 ^ xor_ln54_12_fu_1244_p2);

assign xor_ln63_2_fu_1580_p2 = (xor_ln55_6_fu_1458_p2 ^ xor_ln54_15_fu_1452_p2);

assign xor_ln63_fu_758_p2 = (xor_ln55_fu_612_p2 ^ xor_ln54_9_fu_606_p2);

assign xor_ln94_fu_428_p2 = (xor_reduce_i_7_i_fu_390_p2 ^ xor_reduce_i_6_i_fu_372_p2);

assign xor_ln95_fu_434_p2 = (xor_reduce_i_6_i_fu_372_p2 ^ xor_reduce_i_5_i_fu_354_p2);

assign xor_ln96_1_fu_446_p2 = (xor_reduce_i_4_i_fu_322_p2 ^ xor_ln96_fu_440_p2);

assign xor_ln96_fu_440_p2 = (xor_reduce_i_7_i_fu_390_p2 ^ xor_reduce_i_5_i_fu_354_p2);

always @ (*) begin
    xor_reduce_i_1_i1_fu_1658_p2 = ^(zext_ln85_1_fu_1654_p1);
end

always @ (*) begin
    xor_reduce_i_1_i2_fu_1880_p2 = ^(and_ln117_1_fu_1864_p7);
end

always @ (*) begin
    xor_reduce_i_1_i_fu_208_p2 = ^(zext_ln75_1_fu_204_p1);
end

always @ (*) begin
    xor_reduce_i_2_i1_fu_1700_p2 = ^(and_ln85_2_fu_1684_p7);
end

always @ (*) begin
    xor_reduce_i_2_i2_fu_1902_p2 = ^(and_ln117_2_fu_1886_p7);
end

always @ (*) begin
    xor_reduce_i_2_i_fu_244_p2 = ^(and_ln75_2_fu_232_p5);
end

always @ (*) begin
    xor_reduce_i_3_i1_fu_1722_p2 = ^(zext_ln85_2_fu_1718_p1);
end

always @ (*) begin
    xor_reduce_i_3_i2_fu_1924_p2 = ^(and_ln117_3_fu_1908_p7);
end

always @ (*) begin
    xor_reduce_i_3_i_fu_282_p2 = ^(and_ln75_3_fu_270_p5);
end

always @ (*) begin
    xor_reduce_i_4_i1_fu_1748_p2 = ^(zext_ln85_3_fu_1744_p1);
end

always @ (*) begin
    xor_reduce_i_4_i2_fu_1934_p2 = ^(zext_ln117_fu_1930_p1);
end

always @ (*) begin
    xor_reduce_i_4_i_fu_322_p2 = ^(and_ln75_4_fu_306_p7);
end

always @ (*) begin
    xor_reduce_i_5_i1_fu_1780_p2 = ^(zext_ln85_4_fu_1776_p1);
end

always @ (*) begin
    xor_reduce_i_5_i2_fu_1960_p2 = ^(zext_ln117_1_fu_1956_p1);
end

always @ (*) begin
    xor_reduce_i_5_i_fu_354_p2 = ^(and_ln75_5_fu_338_p7);
end

always @ (*) begin
    xor_reduce_i_6_i1_fu_1802_p2 = ^(zext_ln85_5_fu_1798_p1);
end

always @ (*) begin
    xor_reduce_i_6_i2_fu_1986_p2 = ^(zext_ln117_2_fu_1982_p1);
end

always @ (*) begin
    xor_reduce_i_6_i_fu_372_p2 = ^(and_ln75_6_fu_360_p5);
end

always @ (*) begin
    xor_reduce_i_7_i1_fu_1822_p2 = ^(and_ln85_7_fu_1808_p6);
end

always @ (*) begin
    xor_reduce_i_7_i2_fu_2008_p2 = ^(and_ln117_6_fu_1992_p7);
end

always @ (*) begin
    xor_reduce_i_7_i_fu_390_p2 = ^(and_ln75_7_fu_378_p5);
end

always @ (*) begin
    xor_reduce_i_i1_fu_1640_p2 = ^(zext_ln85_fu_1636_p1);
end

always @ (*) begin
    xor_reduce_i_i2_fu_1858_p2 = ^(and_ln5_fu_1842_p7);
end

always @ (*) begin
    xor_reduce_i_i_fu_166_p2 = ^(zext_ln75_fu_162_p1);
end

assign y0_1_fu_408_p3 = {{xor_reduce_i_5_i_fu_354_p2}, {xor_reduce_i_4_i_fu_322_p2}};

assign y0_fu_528_p3 = {{xor_reduce_i_1_i_fu_208_p2}, {xor_reduce_i_i_fu_166_p2}};

assign y1_1_fu_1174_p3 = {{xor_reduce_i_7_i_fu_390_p2}, {xor_reduce_i_6_i_fu_372_p2}};

assign y1_fu_520_p3 = {{xor_reduce_i_3_i_fu_282_p2}, {xor_reduce_i_2_i_fu_244_p2}};

assign y_12_fu_2014_p9 = {{{{{{{{xor_reduce_i_7_i2_fu_2008_p2}, {xor_reduce_i_6_i2_fu_1986_p2}}, {xor_reduce_i_5_i2_fu_1960_p2}}, {xor_reduce_i_4_i2_fu_1934_p2}}, {xor_reduce_i_3_i2_fu_1924_p2}}, {xor_reduce_i_2_i2_fu_1902_p2}}, {xor_reduce_i_1_i2_fu_1880_p2}}, {xor_reduce_i_i2_fu_1858_p2}};

assign y_13_fu_476_p5 = {{{{xor_ln105_fu_452_p2}, {xor_ln106_2_fu_470_p2}}, {xor_reduce_i_7_i_fu_390_p2}}, {xor_ln94_fu_428_p2}};

assign y_14_fu_1394_p3 = {{xor_ln63_1_fu_1388_p2}, {xor_ln54_12_fu_1244_p2}};

assign y_15_fu_1586_p3 = {{xor_ln63_2_fu_1580_p2}, {xor_ln54_15_fu_1452_p2}};

assign y_22_cast_fu_1828_p6 = {{{{{xor_reduce_i_4_i1_fu_1748_p2}, {xor_reduce_i_3_i1_fu_1722_p2}}, {xor_reduce_i_2_i1_fu_1700_p2}}, {xor_reduce_i_1_i1_fu_1658_p2}}, {xor_reduce_i_i1_fu_1640_p2}};

assign y_3_fu_548_p2 = (y1_fu_520_p3 ^ y0_fu_528_p3);

assign y_7_fu_1194_p2 = (y1_1_fu_1174_p3 ^ y0_1_fu_408_p3);

assign y_fu_764_p3 = {{xor_ln63_fu_758_p2}, {xor_ln54_9_fu_606_p2}};

assign zext_ln117_1_fu_1956_p1 = and_ln117_4_fu_1940_p7;

assign zext_ln117_2_fu_1982_p1 = and_ln117_5_fu_1966_p7;

assign zext_ln117_fu_1930_p1 = y_22_cast_fu_1828_p6;

assign zext_ln75_1_fu_204_p1 = and_ln75_1_fu_188_p7;

assign zext_ln75_fu_162_p1 = and_ln_fu_152_p4;

assign zext_ln85_1_fu_1654_p1 = and_ln85_1_fu_1646_p3;

assign zext_ln85_2_fu_1718_p1 = and_ln85_3_fu_1706_p5;

assign zext_ln85_3_fu_1744_p1 = and_ln85_4_fu_1728_p7;

assign zext_ln85_4_fu_1776_p1 = and_ln85_5_fu_1762_p6;

assign zext_ln85_5_fu_1798_p1 = and_ln85_6_fu_1786_p5;

assign zext_ln85_fu_1636_p1 = and_ln4_fu_1620_p7;

assign ap_return = (y_12_fu_2014_p9 ^ 8'd99);

assign icmp_ln155_1_fu_906_p2 = ((and_ln155_1_fu_896_p4 == 4'd9) ? 1'b1 : 1'b0);

assign icmp_ln155_fu_880_p2 = ((and_ln1_fu_872_p3 == 4'd14) ? 1'b1 : 1'b0);

assign icmp_ln156_1_fu_994_p2 = ((and_ln156_1_fu_986_p3 == 3'd6) ? 1'b1 : 1'b0);

assign icmp_ln156_fu_952_p2 = ((and_ln2_fu_942_p4 == 4'd13) ? 1'b1 : 1'b0);

assign icmp_ln157_1_fu_1046_p2 = ((and_ln157_1_fu_1036_p4 == 4'd11) ? 1'b1 : 1'b0);

assign icmp_ln157_2_fu_1066_p2 = ((and_ln157_2_fu_1056_p4 == 3'd5) ? 1'b1 : 1'b0);

assign icmp_ln157_fu_1026_p2 = ((and_ln3_fu_1014_p5 == 4'd10) ? 1'b1 : 1'b0);

assign icmp_ln158_fu_1122_p2 = ((xor_ln181_3_fu_842_p2 == 3'd7) ? 1'b1 : 1'b0);

endmodule //AES128Encrypt_Sbox
