// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module AES128Encrypt_MixColumns (
        ap_ready,
        state_0_read,
        state_1_read,
        state_2_read,
        state_3_read,
        state_4_read,
        state_5_read,
        state_6_read,
        state_7_read,
        state_8_read,
        state_9_read,
        state_10_read,
        state_11_read,
        state_1213_read,
        state_13_read,
        state_14_read,
        state_15_read,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15
);


output   ap_ready;
input  [7:0] state_0_read;
input  [7:0] state_1_read;
input  [7:0] state_2_read;
input  [7:0] state_3_read;
input  [7:0] state_4_read;
input  [7:0] state_5_read;
input  [7:0] state_6_read;
input  [7:0] state_7_read;
input  [7:0] state_8_read;
input  [7:0] state_9_read;
input  [7:0] state_10_read;
input  [7:0] state_11_read;
input  [7:0] state_1213_read;
input  [7:0] state_13_read;
input  [7:0] state_14_read;
input  [7:0] state_15_read;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
output  [7:0] ap_return_2;
output  [7:0] ap_return_3;
output  [7:0] ap_return_4;
output  [7:0] ap_return_5;
output  [7:0] ap_return_6;
output  [7:0] ap_return_7;
output  [7:0] ap_return_8;
output  [7:0] ap_return_9;
output  [7:0] ap_return_10;
output  [7:0] ap_return_11;
output  [7:0] ap_return_12;
output  [7:0] ap_return_13;
output  [7:0] ap_return_14;
output  [7:0] ap_return_15;

wire   [7:0] y_fu_140_p2;
wire   [0:0] tmp_fu_146_p3;
wire   [7:0] y_16_fu_154_p2;
wire   [7:0] y_18_fu_168_p2;
wire   [0:0] tmp_38_fu_174_p3;
wire   [7:0] y_19_fu_182_p2;
wire   [7:0] y_21_fu_196_p2;
wire   [0:0] tmp_39_fu_202_p3;
wire   [7:0] y_22_fu_210_p2;
wire   [7:0] y_24_fu_224_p2;
wire   [0:0] tmp_40_fu_230_p3;
wire   [7:0] y_25_fu_238_p2;
wire   [7:0] y_64_fu_188_p3;
wire   [7:0] xor_ln142_1_fu_258_p2;
wire   [7:0] y_63_fu_160_p3;
wire   [7:0] xor_ln142_2_fu_264_p2;
wire   [7:0] xor_ln142_fu_252_p2;
wire   [7:0] y_65_fu_216_p3;
wire   [7:0] xor_ln143_1_fu_282_p2;
wire   [7:0] xor_ln143_2_fu_288_p2;
wire   [7:0] xor_ln143_fu_276_p2;
wire   [7:0] xor_ln144_fu_300_p2;
wire   [7:0] y_66_fu_244_p3;
wire   [7:0] xor_ln144_2_fu_312_p2;
wire   [7:0] xor_ln144_1_fu_306_p2;
wire   [7:0] xor_ln145_1_fu_330_p2;
wire   [7:0] xor_ln145_fu_324_p2;
wire   [7:0] y_27_fu_342_p2;
wire   [0:0] tmp_41_fu_348_p3;
wire   [7:0] y_28_fu_356_p2;
wire   [7:0] y_30_fu_370_p2;
wire   [0:0] tmp_42_fu_376_p3;
wire   [7:0] y_31_fu_384_p2;
wire   [7:0] y_33_fu_398_p2;
wire   [0:0] tmp_43_fu_404_p3;
wire   [7:0] y_34_fu_412_p2;
wire   [7:0] y_36_fu_426_p2;
wire   [0:0] tmp_44_fu_432_p3;
wire   [7:0] y_37_fu_440_p2;
wire   [7:0] y_68_fu_390_p3;
wire   [7:0] xor_ln142_5_fu_460_p2;
wire   [7:0] y_67_fu_362_p3;
wire   [7:0] xor_ln142_6_fu_466_p2;
wire   [7:0] xor_ln142_4_fu_454_p2;
wire   [7:0] y_69_fu_418_p3;
wire   [7:0] xor_ln143_5_fu_484_p2;
wire   [7:0] xor_ln143_6_fu_490_p2;
wire   [7:0] xor_ln143_4_fu_478_p2;
wire   [7:0] xor_ln144_4_fu_502_p2;
wire   [7:0] y_70_fu_446_p3;
wire   [7:0] xor_ln144_6_fu_514_p2;
wire   [7:0] xor_ln144_5_fu_508_p2;
wire   [7:0] xor_ln145_4_fu_532_p2;
wire   [7:0] xor_ln145_3_fu_526_p2;
wire   [7:0] y_39_fu_544_p2;
wire   [0:0] tmp_45_fu_550_p3;
wire   [7:0] y_40_fu_558_p2;
wire   [7:0] y_42_fu_572_p2;
wire   [0:0] tmp_46_fu_578_p3;
wire   [7:0] y_43_fu_586_p2;
wire   [7:0] y_45_fu_600_p2;
wire   [0:0] tmp_47_fu_606_p3;
wire   [7:0] y_46_fu_614_p2;
wire   [7:0] y_48_fu_628_p2;
wire   [0:0] tmp_48_fu_634_p3;
wire   [7:0] y_49_fu_642_p2;
wire   [7:0] y_72_fu_592_p3;
wire   [7:0] xor_ln142_9_fu_662_p2;
wire   [7:0] y_71_fu_564_p3;
wire   [7:0] xor_ln142_10_fu_668_p2;
wire   [7:0] xor_ln142_8_fu_656_p2;
wire   [7:0] y_73_fu_620_p3;
wire   [7:0] xor_ln143_9_fu_686_p2;
wire   [7:0] xor_ln143_10_fu_692_p2;
wire   [7:0] xor_ln143_8_fu_680_p2;
wire   [7:0] xor_ln144_8_fu_704_p2;
wire   [7:0] y_74_fu_648_p3;
wire   [7:0] xor_ln144_10_fu_716_p2;
wire   [7:0] xor_ln144_9_fu_710_p2;
wire   [7:0] xor_ln145_7_fu_734_p2;
wire   [7:0] xor_ln145_6_fu_728_p2;
wire   [7:0] y_51_fu_746_p2;
wire   [0:0] tmp_49_fu_752_p3;
wire   [7:0] y_52_fu_760_p2;
wire   [7:0] y_54_fu_774_p2;
wire   [0:0] tmp_50_fu_780_p3;
wire   [7:0] y_55_fu_788_p2;
wire   [7:0] y_57_fu_802_p2;
wire   [0:0] tmp_51_fu_808_p3;
wire   [7:0] y_58_fu_816_p2;
wire   [7:0] y_60_fu_830_p2;
wire   [0:0] tmp_52_fu_836_p3;
wire   [7:0] y_61_fu_844_p2;
wire   [7:0] y_76_fu_794_p3;
wire   [7:0] xor_ln142_13_fu_864_p2;
wire   [7:0] y_75_fu_766_p3;
wire   [7:0] xor_ln142_14_fu_870_p2;
wire   [7:0] xor_ln142_12_fu_858_p2;
wire   [7:0] y_77_fu_822_p3;
wire   [7:0] xor_ln143_13_fu_888_p2;
wire   [7:0] xor_ln143_14_fu_894_p2;
wire   [7:0] xor_ln143_12_fu_882_p2;
wire   [7:0] xor_ln144_12_fu_906_p2;
wire   [7:0] y_78_fu_850_p3;
wire   [7:0] xor_ln144_14_fu_918_p2;
wire   [7:0] xor_ln144_13_fu_912_p2;
wire   [7:0] xor_ln145_10_fu_936_p2;
wire   [7:0] xor_ln145_9_fu_930_p2;
wire   [7:0] next_state_fu_270_p2;
wire   [7:0] next_state_1_fu_294_p2;
wire   [7:0] next_state_2_fu_318_p2;
wire   [7:0] next_state_3_fu_336_p2;
wire   [7:0] next_state_4_fu_472_p2;
wire   [7:0] next_state_5_fu_496_p2;
wire   [7:0] next_state_6_fu_520_p2;
wire   [7:0] next_state_7_fu_538_p2;
wire   [7:0] next_state_8_fu_674_p2;
wire   [7:0] next_state_9_fu_698_p2;
wire   [7:0] next_state_10_fu_722_p2;
wire   [7:0] next_state_11_fu_740_p2;
wire   [7:0] next_state_12_fu_876_p2;
wire   [7:0] next_state_13_fu_900_p2;
wire   [7:0] next_state_14_fu_924_p2;
wire   [7:0] next_state_15_fu_942_p2;

assign ap_ready = 1'b1;

assign next_state_10_fu_722_p2 = (xor_ln144_9_fu_710_p2 ^ xor_ln144_10_fu_716_p2);

assign next_state_11_fu_740_p2 = (xor_ln145_7_fu_734_p2 ^ xor_ln145_6_fu_728_p2);

assign next_state_12_fu_876_p2 = (xor_ln142_14_fu_870_p2 ^ xor_ln142_12_fu_858_p2);

assign next_state_13_fu_900_p2 = (xor_ln143_14_fu_894_p2 ^ xor_ln143_12_fu_882_p2);

assign next_state_14_fu_924_p2 = (xor_ln144_14_fu_918_p2 ^ xor_ln144_13_fu_912_p2);

assign next_state_15_fu_942_p2 = (xor_ln145_9_fu_930_p2 ^ xor_ln145_10_fu_936_p2);

assign next_state_1_fu_294_p2 = (xor_ln143_fu_276_p2 ^ xor_ln143_2_fu_288_p2);

assign next_state_2_fu_318_p2 = (xor_ln144_2_fu_312_p2 ^ xor_ln144_1_fu_306_p2);

assign next_state_3_fu_336_p2 = (xor_ln145_fu_324_p2 ^ xor_ln145_1_fu_330_p2);

assign next_state_4_fu_472_p2 = (xor_ln142_6_fu_466_p2 ^ xor_ln142_4_fu_454_p2);

assign next_state_5_fu_496_p2 = (xor_ln143_6_fu_490_p2 ^ xor_ln143_4_fu_478_p2);

assign next_state_6_fu_520_p2 = (xor_ln144_6_fu_514_p2 ^ xor_ln144_5_fu_508_p2);

assign next_state_7_fu_538_p2 = (xor_ln145_4_fu_532_p2 ^ xor_ln145_3_fu_526_p2);

assign next_state_8_fu_674_p2 = (xor_ln142_8_fu_656_p2 ^ xor_ln142_10_fu_668_p2);

assign next_state_9_fu_698_p2 = (xor_ln143_8_fu_680_p2 ^ xor_ln143_10_fu_692_p2);

assign next_state_fu_270_p2 = (xor_ln142_fu_252_p2 ^ xor_ln142_2_fu_264_p2);

assign tmp_38_fu_174_p3 = state_1_read[32'd7];

assign tmp_39_fu_202_p3 = state_2_read[32'd7];

assign tmp_40_fu_230_p3 = state_3_read[32'd7];

assign tmp_41_fu_348_p3 = state_4_read[32'd7];

assign tmp_42_fu_376_p3 = state_5_read[32'd7];

assign tmp_43_fu_404_p3 = state_6_read[32'd7];

assign tmp_44_fu_432_p3 = state_7_read[32'd7];

assign tmp_45_fu_550_p3 = state_8_read[32'd7];

assign tmp_46_fu_578_p3 = state_9_read[32'd7];

assign tmp_47_fu_606_p3 = state_10_read[32'd7];

assign tmp_48_fu_634_p3 = state_11_read[32'd7];

assign tmp_49_fu_752_p3 = state_1213_read[32'd7];

assign tmp_50_fu_780_p3 = state_13_read[32'd7];

assign tmp_51_fu_808_p3 = state_14_read[32'd7];

assign tmp_52_fu_836_p3 = state_15_read[32'd7];

assign tmp_fu_146_p3 = state_0_read[32'd7];

assign xor_ln142_10_fu_668_p2 = (y_71_fu_564_p3 ^ xor_ln142_9_fu_662_p2);

assign xor_ln142_12_fu_858_p2 = (state_14_read ^ state_13_read);

assign xor_ln142_13_fu_864_p2 = (y_76_fu_794_p3 ^ state_15_read);

assign xor_ln142_14_fu_870_p2 = (y_75_fu_766_p3 ^ xor_ln142_13_fu_864_p2);

assign xor_ln142_1_fu_258_p2 = (y_64_fu_188_p3 ^ state_3_read);

assign xor_ln142_2_fu_264_p2 = (y_63_fu_160_p3 ^ xor_ln142_1_fu_258_p2);

assign xor_ln142_4_fu_454_p2 = (state_6_read ^ state_5_read);

assign xor_ln142_5_fu_460_p2 = (y_68_fu_390_p3 ^ state_7_read);

assign xor_ln142_6_fu_466_p2 = (y_67_fu_362_p3 ^ xor_ln142_5_fu_460_p2);

assign xor_ln142_8_fu_656_p2 = (state_9_read ^ state_10_read);

assign xor_ln142_9_fu_662_p2 = (y_72_fu_592_p3 ^ state_11_read);

assign xor_ln142_fu_252_p2 = (state_2_read ^ state_1_read);

assign xor_ln143_10_fu_692_p2 = (xor_ln143_9_fu_686_p2 ^ state_11_read);

assign xor_ln143_12_fu_882_p2 = (state_14_read ^ state_1213_read);

assign xor_ln143_13_fu_888_p2 = (y_77_fu_822_p3 ^ y_76_fu_794_p3);

assign xor_ln143_14_fu_894_p2 = (xor_ln143_13_fu_888_p2 ^ state_15_read);

assign xor_ln143_1_fu_282_p2 = (y_65_fu_216_p3 ^ y_64_fu_188_p3);

assign xor_ln143_2_fu_288_p2 = (xor_ln143_1_fu_282_p2 ^ state_3_read);

assign xor_ln143_4_fu_478_p2 = (state_6_read ^ state_4_read);

assign xor_ln143_5_fu_484_p2 = (y_69_fu_418_p3 ^ y_68_fu_390_p3);

assign xor_ln143_6_fu_490_p2 = (xor_ln143_5_fu_484_p2 ^ state_7_read);

assign xor_ln143_8_fu_680_p2 = (state_8_read ^ state_10_read);

assign xor_ln143_9_fu_686_p2 = (y_73_fu_620_p3 ^ y_72_fu_592_p3);

assign xor_ln143_fu_276_p2 = (state_2_read ^ state_0_read);

assign xor_ln144_10_fu_716_p2 = (y_74_fu_648_p3 ^ y_73_fu_620_p3);

assign xor_ln144_12_fu_906_p2 = (state_13_read ^ state_1213_read);

assign xor_ln144_13_fu_912_p2 = (xor_ln144_12_fu_906_p2 ^ state_15_read);

assign xor_ln144_14_fu_918_p2 = (y_78_fu_850_p3 ^ y_77_fu_822_p3);

assign xor_ln144_1_fu_306_p2 = (xor_ln144_fu_300_p2 ^ state_3_read);

assign xor_ln144_2_fu_312_p2 = (y_66_fu_244_p3 ^ y_65_fu_216_p3);

assign xor_ln144_4_fu_502_p2 = (state_5_read ^ state_4_read);

assign xor_ln144_5_fu_508_p2 = (xor_ln144_4_fu_502_p2 ^ state_7_read);

assign xor_ln144_6_fu_514_p2 = (y_70_fu_446_p3 ^ y_69_fu_418_p3);

assign xor_ln144_8_fu_704_p2 = (state_9_read ^ state_8_read);

assign xor_ln144_9_fu_710_p2 = (xor_ln144_8_fu_704_p2 ^ state_11_read);

assign xor_ln144_fu_300_p2 = (state_1_read ^ state_0_read);

assign xor_ln145_10_fu_936_p2 = (y_78_fu_850_p3 ^ y_75_fu_766_p3);

assign xor_ln145_1_fu_330_p2 = (y_66_fu_244_p3 ^ y_63_fu_160_p3);

assign xor_ln145_3_fu_526_p2 = (xor_ln144_4_fu_502_p2 ^ state_6_read);

assign xor_ln145_4_fu_532_p2 = (y_70_fu_446_p3 ^ y_67_fu_362_p3);

assign xor_ln145_6_fu_728_p2 = (xor_ln144_8_fu_704_p2 ^ state_10_read);

assign xor_ln145_7_fu_734_p2 = (y_74_fu_648_p3 ^ y_71_fu_564_p3);

assign xor_ln145_9_fu_930_p2 = (xor_ln144_12_fu_906_p2 ^ state_14_read);

assign xor_ln145_fu_324_p2 = (xor_ln144_fu_300_p2 ^ state_2_read);

assign y_16_fu_154_p2 = (y_fu_140_p2 ^ 8'd27);

assign y_18_fu_168_p2 = state_1_read << 8'd1;

assign y_19_fu_182_p2 = (y_18_fu_168_p2 ^ 8'd27);

assign y_21_fu_196_p2 = state_2_read << 8'd1;

assign y_22_fu_210_p2 = (y_21_fu_196_p2 ^ 8'd27);

assign y_24_fu_224_p2 = state_3_read << 8'd1;

assign y_25_fu_238_p2 = (y_24_fu_224_p2 ^ 8'd27);

assign y_27_fu_342_p2 = state_4_read << 8'd1;

assign y_28_fu_356_p2 = (y_27_fu_342_p2 ^ 8'd27);

assign y_30_fu_370_p2 = state_5_read << 8'd1;

assign y_31_fu_384_p2 = (y_30_fu_370_p2 ^ 8'd27);

assign y_33_fu_398_p2 = state_6_read << 8'd1;

assign y_34_fu_412_p2 = (y_33_fu_398_p2 ^ 8'd27);

assign y_36_fu_426_p2 = state_7_read << 8'd1;

assign y_37_fu_440_p2 = (y_36_fu_426_p2 ^ 8'd27);

assign y_39_fu_544_p2 = state_8_read << 8'd1;

assign y_40_fu_558_p2 = (y_39_fu_544_p2 ^ 8'd27);

assign y_42_fu_572_p2 = state_9_read << 8'd1;

assign y_43_fu_586_p2 = (y_42_fu_572_p2 ^ 8'd27);

assign y_45_fu_600_p2 = state_10_read << 8'd1;

assign y_46_fu_614_p2 = (y_45_fu_600_p2 ^ 8'd27);

assign y_48_fu_628_p2 = state_11_read << 8'd1;

assign y_49_fu_642_p2 = (y_48_fu_628_p2 ^ 8'd27);

assign y_51_fu_746_p2 = state_1213_read << 8'd1;

assign y_52_fu_760_p2 = (y_51_fu_746_p2 ^ 8'd27);

assign y_54_fu_774_p2 = state_13_read << 8'd1;

assign y_55_fu_788_p2 = (y_54_fu_774_p2 ^ 8'd27);

assign y_57_fu_802_p2 = state_14_read << 8'd1;

assign y_58_fu_816_p2 = (y_57_fu_802_p2 ^ 8'd27);

assign y_60_fu_830_p2 = state_15_read << 8'd1;

assign y_61_fu_844_p2 = (y_60_fu_830_p2 ^ 8'd27);

assign y_63_fu_160_p3 = ((tmp_fu_146_p3[0:0] == 1'b1) ? y_16_fu_154_p2 : y_fu_140_p2);

assign y_64_fu_188_p3 = ((tmp_38_fu_174_p3[0:0] == 1'b1) ? y_19_fu_182_p2 : y_18_fu_168_p2);

assign y_65_fu_216_p3 = ((tmp_39_fu_202_p3[0:0] == 1'b1) ? y_22_fu_210_p2 : y_21_fu_196_p2);

assign y_66_fu_244_p3 = ((tmp_40_fu_230_p3[0:0] == 1'b1) ? y_25_fu_238_p2 : y_24_fu_224_p2);

assign y_67_fu_362_p3 = ((tmp_41_fu_348_p3[0:0] == 1'b1) ? y_28_fu_356_p2 : y_27_fu_342_p2);

assign y_68_fu_390_p3 = ((tmp_42_fu_376_p3[0:0] == 1'b1) ? y_31_fu_384_p2 : y_30_fu_370_p2);

assign y_69_fu_418_p3 = ((tmp_43_fu_404_p3[0:0] == 1'b1) ? y_34_fu_412_p2 : y_33_fu_398_p2);

assign y_70_fu_446_p3 = ((tmp_44_fu_432_p3[0:0] == 1'b1) ? y_37_fu_440_p2 : y_36_fu_426_p2);

assign y_71_fu_564_p3 = ((tmp_45_fu_550_p3[0:0] == 1'b1) ? y_40_fu_558_p2 : y_39_fu_544_p2);

assign y_72_fu_592_p3 = ((tmp_46_fu_578_p3[0:0] == 1'b1) ? y_43_fu_586_p2 : y_42_fu_572_p2);

assign y_73_fu_620_p3 = ((tmp_47_fu_606_p3[0:0] == 1'b1) ? y_46_fu_614_p2 : y_45_fu_600_p2);

assign y_74_fu_648_p3 = ((tmp_48_fu_634_p3[0:0] == 1'b1) ? y_49_fu_642_p2 : y_48_fu_628_p2);

assign y_75_fu_766_p3 = ((tmp_49_fu_752_p3[0:0] == 1'b1) ? y_52_fu_760_p2 : y_51_fu_746_p2);

assign y_76_fu_794_p3 = ((tmp_50_fu_780_p3[0:0] == 1'b1) ? y_55_fu_788_p2 : y_54_fu_774_p2);

assign y_77_fu_822_p3 = ((tmp_51_fu_808_p3[0:0] == 1'b1) ? y_58_fu_816_p2 : y_57_fu_802_p2);

assign y_78_fu_850_p3 = ((tmp_52_fu_836_p3[0:0] == 1'b1) ? y_61_fu_844_p2 : y_60_fu_830_p2);

assign y_fu_140_p2 = state_0_read << 8'd1;

assign ap_return_0 = next_state_fu_270_p2;

assign ap_return_1 = next_state_1_fu_294_p2;

assign ap_return_10 = next_state_10_fu_722_p2;

assign ap_return_11 = next_state_11_fu_740_p2;

assign ap_return_12 = next_state_12_fu_876_p2;

assign ap_return_13 = next_state_13_fu_900_p2;

assign ap_return_14 = next_state_14_fu_924_p2;

assign ap_return_15 = next_state_15_fu_942_p2;

assign ap_return_2 = next_state_2_fu_318_p2;

assign ap_return_3 = next_state_3_fu_336_p2;

assign ap_return_4 = next_state_4_fu_472_p2;

assign ap_return_5 = next_state_5_fu_496_p2;

assign ap_return_6 = next_state_6_fu_520_p2;

assign ap_return_7 = next_state_7_fu_538_p2;

assign ap_return_8 = next_state_8_fu_674_p2;

assign ap_return_9 = next_state_9_fu_698_p2;

endmodule //AES128Encrypt_MixColumns
